name: Godot CI/CD Pipeline

on: [push, pull_request]

env:
  GODOT_VERSION: "4.2.1"
  GODOT_STATUS: "stable"
jobs:
  import-assets:
    runs-on: ubuntu-latest
    container: barichello/godot-ci:4.2.1
    steps:
      - uses: actions/checkout@v4
      - name: Cache import assets
        uses: actions/cache@v3
        with:
          path: .godot/imported/
          key: import-assets-${{ runner.os }}-${{ github.sha }}
      - name: Import assets
        run: godot --headless --verbose --editor --quit

  export-game:
    runs-on: ubuntu-latest
    needs: import-assets
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: .godot/imported/
          key: import-assets-${{ runner.os }}-${{ github.sha }}
      - name: install wine
        run: |
          sudo apt install wine64
          echo "WINE_PATH=$(which wine64)" >> $GITHUB_ENV
      - name: Export Game using Godot
        uses: firebelley/godot-export@v5.2.1
        with:
          godot_executable_download_url: "https://github.com/godotengine/godot/releases/download/${{ env.GODOT_VERSION }}-${{ env.GODOT_STATUS }}/Godot_v${{ env.GODOT_VERSION }}-${{ env.GODOT_STATUS }}_linux.x86_64.zip"
          godot_export_templates_download_url: "https://github.com/godotengine/godot/releases/download/${{ env.GODOT_VERSION }}-${{ env.GODOT_STATUS }}/Godot_v${{ env.GODOT_VERSION }}-${{ env.GODOT_STATUS }}_export_templates.tpz"
          relative_project_path: "./"
          archive_output: false
          cache: true
          wine_path: ${{ env.WINE_PATH }}
      - name: Upload Windows 64bit
        uses: actions/upload-artifact@v4
        with:
          name: Windows 64bit
          path: ${{ github.workspace }}/output/Windows 64bit
      - name: Upload Windows 32bit
        uses: actions/upload-artifact@v4
        with:
          name: Windows 32bit
          path: ${{ github.workspace }}/output/Windows 32bit
      - name: Upload HTML5
        uses: actions/upload-artifact@v4
        with:
          name: Make Me Laugh!!! HTML5
          path: ${{ github.workspace }}/output/Web
      - name: Upload MacOS
        uses: actions/upload-artifact@v4
        with:
          name: macOS
          path: /home/runner/.local/share/godot/archives/Make Me Laugh!!! macOS.zip
      - name: Upload Linux 64bit
        uses: actions/upload-artifact@v4
        with:
          name: Make Me Laugh!!! Linux 64bit
          path: ${{ github.workspace }}/output/Linux 64bit
      - name: Upload Linux 32bit
        uses: actions/upload-artifact@v4
        with:
          name: Make Me Laugh!!! Linux 32bit
          path: ${{ github.workspace }}/output/Linux 32bit
      - name: Upload Linux arm64
        uses: actions/upload-artifact@v4
        with:
          name: Make Me Laugh!!! Linux arm64
          path: ${{ github.workspace }}/output/Linux arm64
      - name: Upload Linux arm32
        uses: actions/upload-artifact@v4
        with:
          name: Make Me Laugh!!! Linux arm32
          path: ${{ github.workspace }}/output/Linux arm32

  # deploy-to-itchio-linux:
  #   runs-on: ubuntu-latest
  #   needs: export-game
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/download-artifact@v4
  #       with:
  #         name: LinuxX11_x86_64
  #     - name: Deploy to Itch.io (Linux x86_64)
  #       uses: manleydev/butler-publish-itchio-action@master
  #       env:
  #         BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
  #         CHANNEL: linux
  #         ITCH_GAME: ${{ secrets.ITCHIO_GAME }}
  #         ITCH_USER: ${{ secrets.ITCHIO_USERNAME }}
  #         PACKAGE: Make Me Laugh!!! Linux x86_64.zip

  # deploy-to-itchio-windows:
  #   runs-on: ubuntu-latest
  #   needs: export-game
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/download-artifact@v4
  #       with:
  #         name: Windows_x86_64
  #     - uses: actions/download-artifact@v4
  #       with:
  #         name: Windows_x86_32
  #     - name: Deploy to Itch.io (Windows x86_64)
  #       uses: manleydev/butler-publish-itchio-action@master
  #       env:
  #         BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
  #         CHANNEL: win64
  #         ITCH_GAME: ${{ secrets.ITCHIO_GAME }}
  #         ITCH_USER: ${{ secrets.ITCHIO_USERNAME }}
  #         PACKAGE: Make Me Laugh!!! Win64.zip
  #     - name: Deploy to Itch.io (Windows x86_64)
  #       uses: manleydev/butler-publish-itchio-action@master
  #       env:
  #         BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
  #         CHANNEL: win32
  #         ITCH_GAME: ${{ secrets.ITCHIO_GAME }}
  #         ITCH_USER: ${{ secrets.ITCHIO_USERNAME }}
  #         PACKAGE: Make Me Laugh!!! Win32.zip

  # deploy-to-itchio-mac:
  #   runs-on: ubuntu-latest
  #   needs: export-game
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/download-artifact@v4
  #       with:
  #         name: macOS
  #     - name: Deploy to Itch.io (MacOS)
  #       uses: manleydev/butler-publish-itchio-action@master
  #       env:
  #         BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
  #         CHANNEL: mac
  #         ITCH_GAME: ${{ secrets.ITCHIO_GAME }}
  #         ITCH_USER: ${{ secrets.ITCHIO_USERNAME }}
  #         PACKAGE: Make Me Laugh!!! macOS.zip

  # deploy-to-itchio-web:
  #   runs-on: ubuntu-latest
  #   needs: export-game
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/download-artifact@v4
  #       with:
  #         name: HTML5
  #     - name: Deploy to Itch.io (HTML5)
  #       uses: manleydev/butler-publish-itchio-action@master
  #       env:
  #         BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
  #         CHANNEL: web
  #         ITCH_GAME: ${{ secrets.ITCHIO_GAME }}
  #         ITCH_USER: ${{ secrets.ITCHIO_USERNAME }}
  #         PACKAGE: Make Me Laugh!!! HTML5.zip
